/**
 * plan-calendar.ts
 *
 * Calendar blocks for Plan Master artifacts. Creates a 90-min "[Plan] Work on:
 * …" event in the next open deep-work slot when a v1 is generated, and patches
 * the same event's summary + description when a new version is regenerated.
 *
 * Non-fatal by design: if the calendar client is unavailable, no slot fits, or
 * the API call fails, these helpers log and return null. The artifact itself
 * is still written to Supabase + Drive — the calendar block is best-effort.
 *
 * Uses the shared Gmail/Calendar OAuth client (GMAIL_REFRESH_TOKEN), which
 * already holds `calendar.events` scope (see google-scopes.ts).
 */

import { getCalendarClient, CALENDAR_ID } from "./google-calendar";
import { classifyGoogleError } from "./google-auth";
import { getHallPreferences } from "./hall-preferences";
import {
  listBusyBlocks,
  listUpcomingMeetings,
  findOpenSlots,
  type Slot,
} from "./calendar-slots";

export type PlanBlockInput = {
  objectiveTitle: string;
  artifactTitle: string;
  driveUrl: string | null;
  openQuestions: string[];
  userEmail: string;
  /** @default 90 */
  durationMin?: number;
  /** @default 7 */
  windowDays?: number;
};

export type PlanBlockResult = {
  eventId: string;
  eventLink: string;
  start: string;
  end: string;
};

function buildDescription(args: {
  objectiveTitle: string;
  driveUrl: string | null;
  openQuestions: string[];
  versionNumber?: number;
}): string {
  const lines: string[] = [];
  lines.push(`Objective: ${args.objectiveTitle}`);
  if (args.driveUrl) lines.push(`Artifact: ${args.driveUrl}`);
  if (args.versionNumber != null) lines.push(`Version: v${args.versionNumber}`);
  lines.push(`Generated by plan-master-agent`);
  if (args.openQuestions.length > 0) {
    lines.push("");
    lines.push("Open questions:");
    for (const q of args.openQuestions) lines.push(`• ${q}`);
  }
  return lines.join("\n");
}

function buildSummary(objectiveTitle: string, artifactTitle: string): string {
  return `[Plan] Work on: ${objectiveTitle} — ${artifactTitle}`;
}

/**
 * Find the first deep-work slot that fits `durationMin` in the next
 * `windowDays`. Returns null if nothing fits. Honours the user's working
 * hours, lunch, and meeting buffer from hall_preferences.
 */
async function pickFirstFittingSlot(
  userEmail: string,
  durationMin: number,
  windowDays: number
): Promise<Slot | null> {
  const prefs = await getHallPreferences(userEmail);
  const [busy, meetings] = await Promise.all([
    listBusyBlocks(windowDays, prefs.timezone),
    listUpcomingMeetings(windowDays),
  ]);
  const slots = findOpenSlots(new Date(), windowDays, busy, meetings, prefs);
  return slots.find((s) => s.durationMin >= durationMin) ?? null;
}

/**
 * Create a 90-min calendar block for a v1 artifact. Returns the event id +
 * link so the caller can backfill `objective_artifacts.calendar_event_id`.
 * Returns null (non-fatal) when: no calendar client, no fitting slot in the
 * window, or the API call fails.
 */
export async function createPlanBlock(
  input: PlanBlockInput
): Promise<PlanBlockResult | null> {
  const durationMin = input.durationMin ?? 90;
  const windowDays = input.windowDays ?? 7;

  const cal = getCalendarClient();
  if (!cal) {
    console.warn("plan-calendar: calendar client unavailable — skipping block");
    return null;
  }

  let slot: Slot | null;
  try {
    slot = await pickFirstFittingSlot(input.userEmail, durationMin, windowDays);
  } catch (err) {
    console.error(
      "plan-calendar: slot search failed (non-fatal):",
      err instanceof Error ? err.message : String(err)
    );
    return null;
  }
  if (!slot) {
    console.warn(
      `plan-calendar: no ${durationMin}min slot found in next ${windowDays}d — skipping block`
    );
    return null;
  }

  const prefs = await getHallPreferences(input.userEmail);
  const startIso = slot.start.toISOString();
  const endIso = new Date(slot.start.getTime() + durationMin * 60_000).toISOString();

  try {
    const ev = await cal.events.insert({
      calendarId: CALENDAR_ID,
      requestBody: {
        summary: buildSummary(input.objectiveTitle, input.artifactTitle),
        description: buildDescription({
          objectiveTitle: input.objectiveTitle,
          driveUrl: input.driveUrl,
          openQuestions: input.openQuestions,
          versionNumber: 1,
        }),
        start: { dateTime: startIso, timeZone: prefs.timezone },
        end: { dateTime: endIso, timeZone: prefs.timezone },
        reminders: { useDefault: true },
        colorId: "9", // blueberry — distinct from sage STB blocks
        source: {
          title: "Plan Master",
          url: "https://portal.wearecommonhouse.com/admin/plan",
        },
      },
    });
    if (!ev.data.id || !ev.data.htmlLink) {
      console.error("plan-calendar: event insert returned no id/link");
      return null;
    }
    return {
      eventId: ev.data.id,
      eventLink: ev.data.htmlLink,
      start: startIso,
      end: endIso,
    };
  } catch (err) {
    const kind = classifyGoogleError(err);
    console.error(
      `plan-calendar: events.insert failed (${kind}, non-fatal):`,
      err instanceof Error ? err.message : String(err)
    );
    return null;
  }
}

export type UpdatePlanBlockInput = {
  eventId: string;
  objectiveTitle: string;
  artifactTitle: string;
  driveUrl: string | null;
  openQuestions: string[];
  versionNumber: number;
};

/**
 * Patch an existing plan block's summary + description to reflect the newest
 * version. Time is preserved — the block is the protected time, the version
 * is just metadata. Non-fatal on failure.
 */
export async function updatePlanBlock(
  input: UpdatePlanBlockInput
): Promise<{ ok: true } | null> {
  const cal = getCalendarClient();
  if (!cal) {
    console.warn("plan-calendar: calendar client unavailable — skipping update");
    return null;
  }

  try {
    await cal.events.patch({
      calendarId: CALENDAR_ID,
      eventId: input.eventId,
      requestBody: {
        summary: buildSummary(input.objectiveTitle, input.artifactTitle),
        description: buildDescription({
          objectiveTitle: input.objectiveTitle,
          driveUrl: input.driveUrl,
          openQuestions: input.openQuestions,
          versionNumber: input.versionNumber,
        }),
      },
    });
    return { ok: true };
  } catch (err) {
    const kind = classifyGoogleError(err);
    console.error(
      `plan-calendar: events.patch failed (${kind}, non-fatal):`,
      err instanceof Error ? err.message : String(err)
    );
    return null;
  }
}
