-- Talking-points cache for the Hall "Today's agenda" card.
--
-- Previously the next meeting's talking points were generated by Haiku on
-- EVERY page load (no cache, silent null on failure). One row per calendar
-- event id: generate once, reuse until the meeting passes. Cleanup is
-- implicit — rows for past meetings simply stop being read; a periodic
-- DELETE WHERE meeting_start < now() - interval '30 days' can prune later.

CREATE TABLE IF NOT EXISTS public.hall_talking_points (
  event_id      text PRIMARY KEY,
  points        jsonb NOT NULL,
  meeting_start timestamptz,
  generated_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.hall_talking_points ENABLE ROW LEVEL SECURITY;
-- Service-role only (server components); no anon policies.
