-- Portal 2.0 — incremental state-refresh proposals
--
-- The state-refresh job reads only NEW validated evidence since the last accepted
-- state change and PROPOSES updates. It never writes project_states or
-- project_state_items directly, and never promotes an observation to knowledge.
-- A human accepts or rejects each proposal; acceptance is what mutates state and
-- records a project_state_revisions row with action 'system_refresh'.

create table if not exists public.project_state_proposals (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,

  -- What kind of change is being proposed.
  proposal_kind text not null check (proposal_kind in (
    'add_item', 'update_item', 'resolve_item', 'state_summary', 'add_learning'
  )),

  -- Set for update_item / resolve_item; the existing claim being changed.
  target_item_id uuid references public.project_state_items(id) on delete cascade,

  -- Advisory classification for add_item / new state item_type.
  item_type text,

  summary text not null,      -- one-line human-readable headline of the change
  rationale text not null,    -- the model's reasoning, grounded in evidence
  impact text not null default 'medium'
    check (impact in ('low', 'medium', 'high', 'critical')),
  confidence smallint not null default 50 check (confidence between 0 and 100),

  -- Evidence IDs (public.evidence.id) that justify the proposal. Preserved so an
  -- accepted proposal carries traceable source_refs into the state item.
  source_refs text[] not null default '{}',

  -- Concrete proposed field values, shape depends on proposal_kind. Kept as jsonb
  -- so the table stays narrow while still auditable.
  payload jsonb not null default '{}'::jsonb,

  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected', 'superseded', 'expired')),

  -- The delta window this proposal was generated from — makes the "only new
  -- evidence" guarantee inspectable and prevents re-proposing the same delta.
  evidence_window_start timestamptz,
  evidence_window_end timestamptz,

  generated_by text,          -- e.g. 'job:state-refresh'
  model text,

  -- Backlinks recorded when a proposal is accepted.
  applied_revision_id uuid references public.project_state_revisions(id) on delete set null,
  applied_item_id uuid references public.project_state_items(id) on delete set null,

  reviewed_by text,
  reviewed_at timestamptz,
  review_note text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists project_state_proposals_pending_idx
  on public.project_state_proposals (project_id, created_at desc)
  where status = 'pending';

create index if not exists project_state_proposals_status_idx
  on public.project_state_proposals (status, created_at desc);

alter table public.project_state_proposals enable row level security;
revoke all on public.project_state_proposals from anon, authenticated;

comment on table public.project_state_proposals is
  'Human-gated proposed changes to project current state, generated by the incremental state-refresh job from new validated evidence. Acceptance mutates state; the proposal itself never does.';
